---
sidebar: sidebar 
permalink: rename_storage.html 
keywords:  
summary: Você pode renomear o storage usando a API REST. 
---
= Restaure o backup do armazenamento renomeado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando o armazenamento é renomeado, os fluxos de trabalho usando backups feitos antes do nome usado para falhar. Com a introdução do recurso de backup de renomeação, que é exclusivamente acessível por meio da API REST, agora é possível usar os backups que foram feitos antes da renomeação de armazenamento. O fluxo de trabalho e o uso da API REST são descritos abaixo.

.Passos
. Adicione ou atualize a nova conexão de storage, garantindo que o novo nome do cluster ou SVM seja refletido na VCR.
. Reinicie o serviço para atualizar os caches conforme descrito no artigo da KB: https://kb.netapp.com/mgmt/SnapCenter/SCV_backups_fail_after_SVM_rename["Os backups das VCS falham após o nome da SVM"]
. Crie um novo backup.
. Use os detalhes de backup para encontrar os nomes de armazenamento antigos e novos.
. Na tela *backups* do cliente vSphere, selecione o backup para ver seus detalhes.
. Acesse Swagger a partir do URL: `\https://<SCV-IP>:8144/api/swagger-ui/index.html`
+
Use a seguinte API para renomear o armazenamento:

+
PATCH /4,1/storage-system

+
Clique em "nome": "String", "newSVM": "Nome": "String", "newSVM": "Nome": "String"

+
Resposta:

+
"StatusMessage": "OK", "statusCode": 200, "responseMessage": [ "Sistema de armazenamento renomeado com êxito". ]

+
Depois de executar esta API, você será capaz de executar todos os fluxos de trabalho, incluindo a operação de restauração do backup antigo.


