---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: Quando você anexa um disco virtual para operações de restauração de arquivo convidado ou pasta, a VM de destino para o anexo deve ter credenciais configuradas antes de restaurar. 
---
= Configurar credenciais para restaurações de arquivos convidados VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando você anexa um disco virtual para operações de restauração de arquivo convidado ou pasta, a VM de destino para o anexo deve ter credenciais configuradas antes de restaurar.

.Sobre esta tarefa
A tabela a seguir lista os requisitos de credenciais para operações de restauração de convidados.

|===
|  | Controlo de acesso do utilizador ativado | Controlo de acesso do utilizador desativado 


| Usuário de domínio | Um usuário de domínio com "administrador" como o nome de usuário funciona bem. Por exemplo, "NetApp/administrador". No entanto, um usuário de domínio com "xyz" como o nome de usuário que pertence a um grupo de administrador local não funcionará. Por exemplo, você não pode usar "NetApp". | Ou um usuário de domínio com "administrador" como o nome de usuário ou um usuário de domínio com "xyz" como o nome de usuário que pertence a um grupo de administrador local, funciona bem. Por exemplo, "NetApp/administrator" ou "NetApp/xyz". 


| Utilizador do grupo de trabalho | Um usuário local com "administrador" como o nome de usuário funciona bem. No entanto, um usuário local com "xyz" como o nome de usuário que pertence a um grupo de administrador local não funcionará. | Um usuário local com "administrador" como o nome de usuário ou um usuário local com "xyz" como o nome de usuário que pertence a um grupo de administrador local, funciona bem. No entanto, um usuário local com "xyz" como o nome de usuário que não pertence ao grupo de administrador local não funcionará. 
|===
Nos exemplos anteriores, "NetApp" é o nome de domínio fictício e "xyz" é o nome de usuário local fictício

.Passos
. Na janela atalhos do cliente vSphere, selecione *Plug-in SnapCenter para VMware vSphere* em plug-ins.
. Na navegação à esquerda, selecione *Restauração de arquivo convidado*.
. Na seção *Executar como credenciais*, execute um dos seguintes procedimentos:
+
|===
| Para fazer isso... | Faça isso... 


| Use credenciais existentes | Selecione qualquer uma das credenciais configuradas. 


| Adicionar novas credenciais  a| 
.. Selecione *Adicionar*.
.. Na caixa de diálogo *Executar como credenciais*, insira as credenciais. Para Nome de usuário, você deve digitar "Administrador".
.. Clique em *Select VM* e selecione uma VM na caixa de diálogo *Proxy VM*. Clique em *Salvar* para retornar à caixa de diálogo *Executar como credenciais*. Selecione a VM que deve ser usada para autenticar as credenciais.


|===
+
O plug-in do SnapCenter para VMware vSphere usa as credenciais selecionadas para fazer logon na VM selecionada.

. Clique em *Salvar*.

