---
sidebar: sidebar 
permalink: scpivs44_modify_storage_timeout.html 
keywords:  
summary: Mesmo que os backups tenham sido executados com sucesso no passado, eles podem começar a falhar durante o tempo em que o plug-in do SnapCenter para VMware vSphere deve esperar que o sistema de armazenamento exceda o período de tempo limite configurado. Se esta condição ocorrer, você pode aumentar o tempo limite configurado. 
---
= Modifique o tempo limite de armazenamento configurado
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Mesmo que os backups tenham sido executados com sucesso no passado, eles podem começar a falhar durante o tempo em que o plug-in do SnapCenter para VMware vSphere deve esperar que o sistema de armazenamento exceda o período de tempo limite configurado. Se esta condição ocorrer, você pode aumentar o tempo limite configurado.

Você pode encontrar o erro `Unable to discover resources on SCV: Unable to get storage details for datastore <xxx>…`

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *Storage Systems*.
. Na página sistemas de armazenamento, selecione o sistema de armazenamento a ser modificado e clique em *Editar*.
. No campo tempo limite, aumente o número de segundos.
+

TIP: recomenda-se 180 segundos para ambientes grandes.


