---
sidebar: sidebar 
permalink: scpivs44_download_the_snapcenter_plug-in_for_vmware_vsphere_ova_open_virtual_appliance.html 
keywords:  
summary: Você pode baixar o arquivo .tar para o plug-in do SnapCenter vSphere no site de suporte da NetApp. 
---
= Baixe o Open Virtual Appliance (OVA)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de instalar o Open Virtual Appliance (OVA), adicione o certificado ao vCenter. O arquivo .tar contém os certificados OVA e Entrust root e intermediário, os certificados podem ser encontrados na pasta certificados. A implantação DO OVA é suportada no VMware vCenter 7U1 e superior.

Nas versões do VMware vCenter 7.0.3 e posteriores, o OVA assinado pelo certificado Entrust não é mais confiável. Você precisa executar o procedimento a seguir para resolver o problema.

.Passos
. Para fazer o download do plug-in do SnapCenter para VMware:
+
** Faça login no site de suporte da NetApp ( https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^] ).
** Na lista de produtos, selecione *Plug-in SnapCenter para VMware vSphere* e clique no botão *Download da versão mais recente*.
** Baixe o plug-in do SnapCenter para o arquivo VMware vSphere para `.tar` qualquer local.


. Faça login com o vSphere Client no vCenter Server.
. Navegue até *Administration > Certificates > Certificate Management* (Administração > certificados > Gestão de certificados).
. Ao lado de *Trusted Root Store*, clique em *Add*
. Procure e selecione a localização dos certificados raiz e intermédios Entrust. O certificado é adicionado em um painel em *certificados raiz confiáveis*. Uma vez que os certificados são instalados, OVA pode ser verificado e implantado.



NOTE: Se o OVA baixado não for adulterado, a coluna *Publisher* exibirá *certificado confiável*.
