---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: Você pode criar, modificar, exibir, desanexar e excluir políticas de backup do plug-in do SnapCenter para VMware vSphere. Políticas são necessárias para executar operações de proteção de dados. 
---
= Gerenciar políticas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar, modificar, exibir, desanexar e excluir políticas de backup do plug-in do SnapCenter para VMware vSphere. Políticas são necessárias para executar operações de proteção de dados.



== Desanexe políticas

Você pode separar políticas de um grupo de recursos do plug-in do SnapCenter para VMware vSphere quando não quiser mais que essas políticas governem a proteção de dados para os recursos. Você deve desanexar uma política antes de removê-la ou antes de modificar a frequência da programação.

.Sobre esta tarefa
As diretrizes para separar políticas do plug-in do SnapCenter para grupos de recursos do VMware vSphere diferem das diretrizes para grupos de recursos do SnapCenter. Para um grupo de recursos do cliente VMware vSphere, é possível separar todas as políticas, o que deixa o grupo de recursos sem nenhuma política. No entanto, para executar quaisquer operações de proteção de dados nesse grupo de recursos, é necessário anexar pelo menos uma política.

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *grupos de recursos*, selecione um grupo de recursos e clique em *Editar*.
. Na página *Policies* do assistente *Edit Resource Group*, desmarque a marca de seleção ao lado das políticas que você deseja desanexar.
+
Você também pode adicionar uma política ao grupo de recursos marcando a política.

. Faça quaisquer modificações adicionais ao grupo de recursos no restante do assistente e clique em *Finish*.




== Modificar políticas

Você pode modificar políticas para um grupo de recursos do SnapCenter Plug-in para VMware vSphere. Você pode modificar a frequência, as opções de replicação, as configurações de retenção de instantâneos ou as informações de scripts enquanto uma política é anexada a um grupo de recursos.

.Sobre esta tarefa
Modificar o plug-in do SnapCenter para políticas de backup do VMware vSphere difere de modificar políticas de backup para plug-ins baseados em aplicativos do SnapCenter. Não é necessário separar políticas de grupos de recursos quando você modifica as políticas de plug-in.

Antes de modificar as configurações de replicação ou retenção, você deve considerar as possíveis consequências.

* Aumentar as configurações de replicação ou retenção
+
Os backups continuam se acumulando até que atinjam a nova configuração.

* Diminuir as configurações de replicação ou retenção
+
Os backups em excesso da nova configuração são excluídos quando o próximo backup é executado.




NOTE: Para modificar um agendamento de política do SnapCenter Plug-in para VMware vSphere, você deve modificar a programação no grupo de recursos do plug-in.

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *Policies*, selecione uma política e clique em *Edit*.
. Modifique os campos da política.
. Quando terminar, clique em *Atualizar*.


As alterações entram em vigor quando o próximo backup programado é executado.



== Eliminar políticas

Se você não precisar mais de uma política de backup configurada para o plug-in do SnapCenter para VMware vSphere, talvez queira excluí-la.

.Antes de começar
Você deve ter separado a política de todos os grupos de recursos no dispositivo virtual para SnapCenter antes de excluí-la.

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *políticas*, selecione uma política e clique em *Remover*.
. Na caixa de diálogo de confirmação, clique em *OK*.

