---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: Você pode criar, modificar e excluir grupos de recursos de backup e executar operações de backup em grupos de recursos. 
---
= Gerenciar grupos de recursos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode criar, modificar e excluir grupos de recursos de backup e executar operações de backup em grupos de recursos.


NOTE: Os grupos de recursos são chamados de tarefas de backup no Virtual Storage Console (VSC).



== Suspender e retomar as operações em grupos de recursos

Pausar operações agendadas em um grupo de recursos.  Habilite-os novamente quando necessário.

.Passos
. No painel de navegação esquerdo do plug-in SCV, selecione *grupos de recursos*, selecione um grupo de recursos e selecione *suspender* (ou selecione *Resume*).
. Na caixa de confirmação, selecione *OK* para confirmar.


.Depois de terminar
Na página grupos de recursos , o status da tarefa para o recurso suspenso é `Under_Maintenance`. Talvez seja necessário rolar para a direita da tabela para ver a coluna Status da tarefa.

Depois que as operações de cópia de segurança forem retomadas, o Estado da tarefa muda para `Production`.



== Modificar grupos de recursos

Você pode remover ou adicionar recursos em grupos de recursos no vCenter, desanexar ou anexar políticas, modificar programações ou modificar qualquer outra opção de grupo de recursos.

.Sobre esta tarefa
Se você quiser modificar o nome de um grupo de recursos, não use os seguintes carateres especiais em nomes de VM, datastore, política, backup ou grupo de recursos:

% E * / : * ? " < > - | ; ' , e espaço. Um caractere de sublinhado (_) é permitido.

.Passos
. No painel de navegação esquerdo do plug-in SCV, selecione *grupos de recursos*, selecione um grupo de recursos e selecione *Editar*.
. Na lista à esquerda do assistente *Editar grupo de recursos*, selecione a categoria que deseja modificar e insira suas alterações.
+
Você pode fazer alterações em várias categorias. Você também pode editar recursos protegidos secundários nesta opção.

. Selecione *Next* até ver a página Summary (Resumo) e, em seguida, selecione *Finish* (concluir).




== Eliminar grupos de recursos

Exclua um grupo de recursos no vCenter se não precisar proteger os recursos.  Exclua todos os grupos de recursos antes de remover o SnapCenter Plug-in for VMware vSphere.

.Sobre esta tarefa
Todas as operações de exclusão de grupos de recursos são executadas como exclusões forçadas.  Quando você exclui um grupo de recursos, o sistema desanexa todas as políticas do grupo de recursos do vCenter, remove o grupo de recursos do SnapCenter Plug-in for VMware vSphere e exclui todos os backups e instantâneos do grupo de recursos.


NOTE: Em um relacionamento SnapVault , você não pode excluir o último snapshot, portanto, não pode excluir o grupo de recursos.  Antes de excluir um grupo de recursos em um relacionamento SnapVault , use o System Manager ou o ONTAP CLI para remover o relacionamento e, em seguida, exclua o último snapshot.

.Passos
. No painel de navegação esquerdo do plug-in SCV, selecione *grupos de recursos*, selecione um grupo de recursos e selecione *Excluir*.
. Na caixa de diálogo de confirmação *Excluir grupo de recursos*, selecione *OK* para confirmar.  A exclusão de um grupo de recursos não remove a proteção secundária.  Se necessário, use o Gerenciador do Sistema para excluir a proteção secundária.  Os grupos de consistência criados para o grupo de recursos não são removidos automaticamente; você deve excluí-los manualmente do ONTAP usando o Gerenciador do Sistema ou outra interface compatível.

