---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: Os ONTAP Privileges mínimos necessários variam de acordo com os plug-ins do SnapCenter que você está usando para proteção de dados. 
---
= ONTAP Privileges necessário
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Os ONTAP Privileges mínimos necessários variam de acordo com os plug-ins do SnapCenter que você está usando para proteção de dados.


NOTE: A partir do plug-in do SnapCenter para VMware (SCV) 5,0, é necessário adicionar aplicativos do tipo HTTP e ONTAPI como métodos de login de usuário para qualquer usuário do ONTAP com acesso personalizado baseado em função à SCV. Sem acesso a esses aplicativos, os backups falharão. Você precisa reiniciar o serviço SCV para reconhecer alterações nos métodos de login do usuário do ONTAP.



== Mínimo de ONTAP Privileges necessário

Todos os plug-ins do SnapCenter exigem o seguinte Privileges mínimo.

|===


| Comandos All-Access: Mínimo ONTAP Privileges. 


| event generate-AutoSupport-log 


| o histórico de trabalhos mostra a paragem do trabalho 


| lun lun lun create lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun eleja lun node lun moja lun moja lun moja lun moja lun moja off-line lun off-line lun online persistent-reservation clear lun redimensione serial lun show 


| SnapMirror list-destinations SnapMirror policy add-rule SnapMirror policy modificar-rule SnapMirror policy remover-rule SnapMirror policy show SnapMirror restore SnapMirror show SnapMirror show-history SnapMirror update SnapMirror update-ls-set 


| Versão 


| Clone de volume criar clone de volume show de volume show de volume split start volume clone split status volume split stop volume criar volume excluir volume destruir clone de arquivo de volume criar arquivo de volume show-disco-uso volume off-line volume gerenciado-recurso volume modificar volume criar volume excluir volume qtree modificar volume apagar volume qtree modificar volume SnapLock alterar volume alterar volume alterar volume instantâneo volume alterar volume instantâneo volume alterar volume ampliar volume ampliar volume ampliar volume 


| servidor vnvserver subsystem vnvme servidor vnvme servidor servidor vnvme servidor servidor vnvme servidor servidor vnvme servidor servidor 
|===
|===
| Comandos somente leitura: ONTAP Privileges mínimo 


| a identidade do cluster mostra a interface de rede mostra vserver vserver peer vserver show 
|===
|===
| Comandos All-Access: Mínimo ONTAP Privileges 


| mostra a unidade de armazenamento do grupo de consistência 
|===
Você pode ignorar o comando _cluster identity show_ cluster level ao criar uma função para associar ao data SVM.


NOTE: Você pode ignorar as mensagens de aviso sobre os comandos SVM não suportados.



== Informações adicionais sobre o ONTAP

* Você precisa do ONTAP 9.12,1 ou versões posteriores para usar o recurso de sincronização ativa do SnapMirror.
* Para usar o recurso de Snapshot à prova de violações (TPS):
+
** Você precisa do ONTAP 9.13,1 e versões posteriores para SAN
** Você precisa do ONTAP 9.12,1 e versões posteriores para NFS


* Para NVMe em TCP e NVMe em protocolo FC, você precisa do ONTAP 9.10,1 e posterior.



NOTE: A partir da versão 9.11.1 do ONTAP , a comunicação com o cluster ONTAP é feita por meio de APIs REST.  O usuário do ONTAP deve ter o aplicativo http habilitado.  No entanto, se forem encontrados problemas com as APIs REST do ONTAP , a chave de configuração 'FORCE_ZAPI' ajuda na transição para o fluxo de trabalho ZAPI tradicional.  Talvez seja necessário adicionar ou atualizar essa chave usando as APIs de configuração e defini-la como verdadeira.  Consulte o artigo da KB, https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["Como usar RestAPI para editar parâmetros de configuração no SCV"] para mais informações.
