---
sidebar: sidebar 
permalink: scpivs44_manage_storage_systems.html 
keywords:  
summary: Antes de fazer backup ou restaurar VMs ou armazenamentos de dados usando o cliente VMware vSphere, você deve adicionar o armazenamento. 
---
= Gerenciar sistemas de storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Antes de fazer backup ou restaurar VMs ou armazenamentos de dados usando o cliente VMware vSphere, você deve adicionar o armazenamento.



== Modificar VMs de storage

Você pode usar o cliente VMware vSphere para modificar as configurações de clusters e VMs de storage registradas no plug-in do SnapCenter para VMware vSphere e usadas para operações de proteção de dados de VM.

Se você modificar uma VM de storage que foi adicionada automaticamente como parte de um cluster (às vezes chamada de VM de storage implícita), essa VM de storage será alterada para uma VM de storage explícita e poderá ser excluída separadamente sem alterar o restante das VMs de storage nesse cluster. Na página sistemas de armazenamento, o nome de usuário é exibido como N/A quando o método de autenticação é através do certificado; os nomes de usuário são exibidos apenas para VMs de armazenamento explícitas na lista de cluster e têm o sinalizador ExplicitSVM definido como verdadeiro. Todas as VMs de armazenamento são sempre listadas no cluster associado.


IMPORTANT: Se você adicionou VMs de storage para operações de proteção de dados baseadas em aplicações usando a GUI do SnapCenter, precisará usar a mesma GUI para modificar essas VMs de storage.

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *Storage Systems*.
. Na página *sistemas de armazenamento*, selecione a VM de armazenamento a ser modificada e, em seguida, selecione *Editar*.
. Na janela *Editar sistema de armazenamento*, insira os novos valores e clique em *Atualizar* para aplicar as alterações.




== Remova as VMs de storage

Você pode usar o cliente VMware vSphere para remover VMs de armazenamento do inventário no vCenter.


NOTE: Se você adicionou VMs de storage para operações de proteção de dados baseadas em aplicações usando a GUI do SnapCenter, precisará usar a mesma GUI para modificar essas VMs de storage.

.Antes de começar
É necessário desmontar todos os armazenamentos de dados na VM de storage antes de remover a VM de storage.

.Sobre esta tarefa
Se um grupo de recursos tiver backups que residem em uma VM de storage removida, os backups subsequentes para esse grupo de recursos falharão.

.Passos
. No painel de navegação esquerdo do plug-in SCV, clique em *Storage Systems*.
. Na página *Storage Systems*, selecione a VM de armazenamento a ser removida e clique em *Delete*.
. Na caixa de confirmação *Remover sistema de armazenamento*, marque a caixa *Excluir sistema(s) de armazenamento* e clique em *Sim* para confirmar. *Observação:* somente o host ESXi 7.0U1 e versões posteriores são suportados.
+
link:scpivs44_restart_the_vmware_vsphere_web_client_service.html["Reinicie o serviço cliente VMware vSphere"].


