---
permalink: scv60_releasenotes_60_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.0, 6.0.1' 
summary: Saiba mais sobre os novos recursos disponíveis no plug-in do SnapCenter para VMware vSphere 6,0. 
---
= Novidades do plug-in do SnapCenter para VMware vSphere 6,0
:allow-uri-read: 


[cols="30%,70%"]
|===
| Atualização | Descrição 


 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_concepts_overview.html["Suporte para protocolo NVMe sobre TCP"]
 a| 
O plug-in do SnapCenter para VMware vSphere 6,0 agora oferece suporte ao protocolo NVMe sobre TCP para datastores VMFS.

Você não precisa de nenhum hardware adicional para implantar o NVMe sobre o protocolo TCP, o que o torna mais simples e econômico para você.

Como iSCSI, os armazenamentos de dados VMFS com protocolo NVMe sobre TCP podem usar qualquer NICs e switches ethernet e dar suporte a todas as operações padrão, como backup, restauração, montagem, conexão e desconexão.



 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies_for_vms_and_datastores.html["Suporte para sincronização ativa do SnapMirror"]
 a| 
Agora você pode usar o plug-in do SnapCenter para VMware vSphere para configurar recursos de sincronização ativa do SnapMirror, como objetivo de ponto de recuperação zero (RPO), objetivo de tempo de recuperação (rto) e failover transparente de aplicativos.

A sincronização ativa do SnapMirror é suportada apenas para armazenamentos de dados VMFS.

|===