---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: Saiba mais sobre os novos recursos disponíveis no SnapCenter Plug-in for VMware vSphere 6.2. 
---
= Novidades no SnapCenter Plug-in for VMware vSphere 6.2
:allow-uri-read: 


[role="lead"]
Saiba mais sobre os novos recursos disponíveis no SnapCenter Plug-in for VMware vSphere 6.2.

A versão SnapCenter Plug-in for VMware vSphere 6.2 adiciona suporte para backup e recuperação de máquinas virtuais (VMs) em datastores VMFS para sistemas ASA r2 executando ONTAP 9.17.1 ou posterior.  Com esta versão, você pode executar as seguintes operações para VMs, armazenamentos de dados e formato de disco de máquina virtual (VMDK) em sistemas ASA r2:

* Provisão de grupos de consistência para proteção primária
* Executar backups baseados em grupos de consistência
* Use grupos de consistência hierárquicos (disponíveis com o ONTAP 9.17.1 e versões posteriores)
* Executar fluxos de trabalho de clone
* Executar fluxos de trabalho de restauração
* Provisionar proteção secundária ao criar ou modificar grupos de recursos (disponível com o ONTAP 9.16.1 e versões posteriores)

